---
  - name: "PLAY 1 - RUN PRE AND POST CHECKS, SAVING OUTPUT, WITH A SIMPLE NETWORK CHANGE"
    hosts: "iosxe"
    connection: "network_cli"
    gather_facts: no
    tasks:
      - name: "TASK 1 - RUN PRE CHECKS AND SAVE TO MEMORY" 
        cisco.ios.ios_command:
            commands:
              - "show ip interface brief"
              - "show interfaces"
        register: "show_command_output"

      - name: "TASK 2 - CREATE SHOW_OUTPUTS DIR IF DOES NOT EXIST"
        ansible.builtin.file:
          path: "show_outputs"
          state: "directory"
          mode: 0775
        run_once: true

      - name: "TASK 3 - SAVE PRE CHECK OUTPUT TO FILE"
        ansible.builtin.template:
          src: "show_command.j2"
          dest: "show_outputs/pre_checks_{{ inventory_hostname }}_show_cmds.txt"

      - name: "TASK 4 - CONFIGURE A SIMPLE L3 INTERFACE"
        cisco.ios.ios_config:
          lines:
              - "description configured by Ansible"
              - "ip address 172.4.4.0 255.255.255.255"
          parents: interface Loopback1450

      - name: "TASK 5 - RUN POST CHECKS AND SAVE TO MEMORY"
        cisco.ios.ios_command:
            commands:
              - "show ip interface brief"
              - "show interfaces"
        register: "show_command_output"

      - name: "TASK 6 SAVE POST CHECK OUTPUT TO FILE"
        ansible.builtin.template:
          src: "show_command.j2"
          dest: "show_outputs/post_checks_{{ inventory_hostname }}_show_cmds.txt"